### ISSUE TITLE
crash on startReaderActivity

### ISSUE THREAD

**Issue by SuperBesse** [miLibris/android-milibris-pdf-reader-sdk#4]
Bonjour,

depuis que j'ai mis à jour les outils android, l'application crash sans log d'exception à l'ouverture de la liseuse. 

`AppCompatActivity appCompat = (AppCompatActivity)getCurrentActivity();
    reader.startReaderActivity(appCompat);`

J'ai mis à jour le sdk milibris et même résultat.

En creusant, j'ai une exception levée dans ActivityThread:

`new IllegalStateException("Activity top position already set to onTop=" + onTop);`

Visiblement il est recommandé de rajouter ces flags dans l'intent:

`intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);`

Avez-vous déjà eu ce genre de soucis ? une solution peut être pour m'aider ?

**Comment by MaximeLM** [comment]
Bonjour,

Nous n'avons pas eu ce souci avec notre SDK, et nous n'utilisons pas les flags `FLAG_ACTIVITY_CLEAR_TOP` et `FLAG_ACTIVITY_SINGLE_TOP`.

Ce post semble indiquer que le crash est causé par la gestion de la stack d'activity dans votre application : https://stackoverflow.com/questions/58232799/crash-when-starting-activity-in-android-10
